version = 2

[[repo]]
name = "agent-chat"
remote = "git@github.com:dartworklabs/skills-agent-chat.git"

[[repo]]
name = "architecting"
remote = "git@github.com:dartworklabs/skills-architecting.git"

[[repo]]
name = "coding"
remote = "git@github.com:dartworklabs/skills-coding.git"
